
auth.token=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

defaults.org=technotaau
defaults.project=react-native

defaults.url=https://sentry.io/
