export const API_CONSTANTS = {
    TIMEOUT: 30000,
    RETRY_ATTEMPTS: 3,
    RETRY_DELAY: 1000,
};

export const QUALITY_THRESHOLDS = {
    BLUR: {
        EXCELLENT: 2000,
        GOOD: 1000,
        ACCEPTABLE: 500,
        POOR: 100,
    },
    EXPOSURE: {
        UNDEREXPOSED_THRESHOLD: 0.3,
        OVEREXPOSED_THRESHOLD: 0.7,
        OPTIMAL_RANGE: [0.4, 0.6] as [number, number],
    },
};

export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
};